DELETE FROM "HANGFIRE.COUNTER";
DELETE FROM "HANGFIRE.HASH";
DELETE FROM "HANGFIRE.JOB";
DELETE FROM "HANGFIRE.JOBPARAMETER";
DELETE FROM "HANGFIRE.JOBQUEUE";
DELETE FROM "HANGFIRE.LIST";
DELETE FROM "HANGFIRE.LOCK";
DELETE FROM "HANGFIRE.SERVER";
DELETE FROM "HANGFIRE.SET";
DELETE FROM "HANGFIRE.STATE";

SET GENERATOR HANGFIRE_COUNTER_GENERATOR TO 0;
SET GENERATOR HANGFIRE_HASH_GENERATOR TO 0;
SET GENERATOR HANGFIRE_JOBPARAMETER_GENERATOR TO 0;
SET GENERATOR HANGFIRE_JOBQUEUE_GENERATOR TO 0;
SET GENERATOR HANGFIRE_JOB_GENERATOR TO 0;
SET GENERATOR HANGFIRE_LIST_GENERATOR TO 0;
SET GENERATOR HANGFIRE_SET_GENERATOR TO 0;
SET GENERATOR HANGFIRE_STATE_GENERATOR TO 0;